import { colors, toRem } from '../../../styles/commonStyle';

export const createGoalsStyles = (mainColor) => ({
	page: {
		padding: toRem(18),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(20),
		paddingBottom: toRem(123),
	},
	section: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
	},
	card: {
		backgroundColor: colors.labelBG,
		borderRadius: toRem(14),
		padding: toRem(18),
		border: `1px solid ${mainColor || colors.green}22`,
		boxShadow: `0 6px 18px ${colors.black}20`,
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
	},
	titleHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: toRem(12),
		flexWrap: 'wrap',
	},
	title: {
		fontSize: toRem(22),
		fontWeight: 700,
	},
	description: {
		opacity: 0.8,
		lineHeight: 1.5,
	},
	addButton: {
		padding: `${toRem(12)} ${toRem(18)}`,
		borderRadius: toRem(12),
		border: 'none',
		cursor: 'pointer',
		backgroundColor: mainColor || colors.green,
		color: colors.white,
		fontWeight: 700,
	},
	goalGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
		gap: toRem(16),
	},
	goalCard: {
		backgroundColor: 'rgba(255,255,255,0.04)',
		borderRadius: toRem(14),
		padding: toRem(18),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(12),
		border: `1px solid ${mainColor || colors.green}22`,
	},
	goalHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: toRem(12),
	},
	goalTitle: {
		fontSize: toRem(18),
		fontWeight: 700,
	},
	statusBadge: {
		padding: `${toRem(6)} ${toRem(10)}`,
		borderRadius: toRem(999),
		fontSize: toRem(12),
		fontWeight: 700,
		textTransform: 'uppercase',
	},
	goalMeta: {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr',
		gap: toRem(10),
	},
	metaItem: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(6),
	},
	metaLabel: {
		fontSize: toRem(12),
		opacity: 0.7,
	},
	metaValue: {
		fontSize: toRem(16),
		fontWeight: 700,
	},
	progressBar: {
		width: '100%',
		height: toRem(12),
		borderRadius: toRem(999),
		backgroundColor: 'rgba(255,255,255,0.08)',
		overflow: 'hidden',
	},
	progressFill: {
		height: '100%',
		borderRadius: toRem(999),
		backgroundColor: mainColor || colors.green,
		transition: 'width 0.3s ease',
	},
	actionRow: {
		display: 'flex',
		justifyContent: 'space-between',
		gap: toRem(10),
		flexWrap: 'wrap',
	},
	deleteButton: {
		padding: `${toRem(10)} ${toRem(14)}`,
		borderRadius: toRem(10),
		border: 'none',
		cursor: 'pointer',
		backgroundColor: colors.red,
		color: colors.white,
		fontWeight: 700,
	},
	formRow: {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr',
		gap: toRem(14),
	},
	formRowFull: {
		gridColumn: '1 / -1',
	},
	input: {
		width: '100%',
		padding: `${toRem(12)} ${toRem(14)}`,
		borderRadius: toRem(12),
		border: `1px solid ${colors.inputBorder}`,
		backgroundColor: colors.labelBG,
		color: colors.white,
		outline: 'none',
		fontSize: toRem(14),
	},
	textarea: {
		width: '100%',
		minHeight: toRem(100),
		padding: `${toRem(12)} ${toRem(14)}`,
		borderRadius: toRem(12),
		border: `1px solid ${colors.inputBorder}`,
		backgroundColor: colors.labelBG,
		color: colors.white,
		outline: 'none',
		fontSize: toRem(14),
		resize: 'vertical',
	},
	statusCard: {
		backgroundColor: 'rgba(255,255,255,0.04)',
		borderRadius: toRem(14),
		padding: toRem(18),
		textAlign: 'center',
	},
	statusText: {
		opacity: 0.75,
		lineHeight: 1.6,
	},
});
