import { colors, toRem } from '../../../styles/commonStyle';

export const createGoalsStyles = (mainColor) => ({
	page: {
		padding: toRem(18),
		paddingBottom: toRem(100),
	},
	section: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
	},
	card: {
		borderRadius: toRem(14),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
	},
	pageHeader: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		gap: toRem(12),
		flexWrap: 'wrap',
	},
	goalProgress: {
	},
	goalProgressTitle: {
		fontSize: toRem(20),
		fontWeight: 700,
		paddingBottom: toRem(15),
	},
	goalProgressCard: {
		width: '100%',
		borderRadius: toRem(14),
		padding: toRem(18),
		border: `1px solid ${mainColor || colors.green}22`,
		boxShadow: `0 6px 18px ${colors.black}20`,
		display: 'flex',
		alignItems: 'center',
		flexWrap: 'wrap',
		gap: toRem(20),
	},
	ellipseProgressWrap: {
		position: 'relative',
		width: toRem(180),
		height: toRem(180),
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	ellipseProgressSvg: {
		transform: 'rotate(-90deg)',
		overflow: 'visible',
	},
	ellipseProgressTrack: {
		fill: 'none',
		stroke: 'rgba(255, 255, 255, 0.08)',
		strokeWidth: toRem(24),
	},
	ellipseProgressFill: {
		fill: 'none',
		stroke: mainColor || colors.green,
		strokeWidth: toRem(24),
		strokeLinecap: 'round',
		transition: 'stroke-dashoffset 0.4s ease, stroke 0.3s ease',
		transformOrigin: 'center',
	},
	ellipseProgressCenter: {
		position: 'absolute',
		inset: 0,
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: toRem(6),
		textAlign: 'center',
		padding: toRem(20),
	},
	ellipseProgressValue: {
		fontSize: toRem(28),
		fontWeight: 800,
		lineHeight: 1,
	},
	ellipseProgressLabel: {
		fontSize: toRem(18),
		opacity: 0.72,
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
	},
	goalProgressContext: {
		flex: '1 1 auto',
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(12),
	},
	goalProgressrow: {
		display: 'flex',
		width: '100%',
		alignItems: 'center',
		gap: toRem(10),
	},
	goalProgressDott: {
		width: toRem(10),
		height: toRem(10),
		borderRadius: '50%',
	},
	goalProgressName: {
		fontWeight: 500,
	},
	goalProgressValue: {
		flex: '1 1 auto',
		textAlign: 'right',
	},
	title: {
		fontSize: toRem(22),
		fontWeight: 700,
	},
	description: {
		opacity: 0.8,
		lineHeight: 1.5,
	},
	addButton: {
		padding: `${toRem(20)} ${toRem(18)}`,
		borderRadius: toRem(12),
		border: toRem(1) + ' solid ' + (mainColor || colors.green),
		cursor: 'pointer',
		color: mainColor,
	},
	newGoalAddButton: {
		padding: `${toRem(20)} ${toRem(18)}`,
		borderRadius: toRem(12),
		border: toRem(1) + ' solid ' + (mainColor || colors.green),
		cursor: 'pointer',
		backgroundColor: mainColor || colors.green,
		fontWeight: 700,
	},
	goalGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
		gap: toRem(16),
	},
	goalCard: {
		backgroundColor: 'rgba(255,255,255,0.04)',
		borderRadius: toRem(14),
		padding: toRem(18),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(12),
		border: `1px solid ${mainColor || colors.green}22`,
	},
	goalHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: toRem(12),
	},
	goalTitle: {
		color: colors.white,
		fontSize: toRem(24),
		fontWeight: 700,
	},
	statusBadge: {
		padding: `${toRem(6)} ${toRem(12)}`,
		borderRadius: toRem(999),
		fontSize: toRem(12),
		fontWeight: 500,
		borderWidth: toRem(1),
		borderStyle: 'solid',
		whiteSpace: 'nowrap',
	},
	goalMeta: {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr',
		gap: toRem(10),
	},
	metaItem: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(6),
	},
	metaLabel: {
		fontSize: toRem(12),
		opacity: 0.7,
		color: colors.white,
	},
	metaValue: {
		fontSize: toRem(16),
		fontWeight: 700,
	},
	progressBar: {
		width: '100%',
		height: toRem(12),
		borderRadius: toRem(999),
		backgroundColor: 'rgba(255,255,255,0.08)',
		overflow: 'hidden',
	},
	progressPercent: {
		fontWeight: 700,
		fontSize: toRem(16),
	},
	progressFill: {
		height: '100%',
		borderRadius: toRem(999),
		transition: 'width 0.3s ease',
	},
	actionRow: {
		display: 'flex',
		justifyContent: 'space-between',
		gap: toRem(10),
		flexWrap: 'wrap',
	},
	deleteButton: {
		padding: `${toRem(10)} ${toRem(14)}`,
		borderRadius: toRem(10),
		border: 'none',
		cursor: 'pointer',
		backgroundColor: colors.red,
		color: colors.white,
		fontWeight: 700,
	},
	formRow: {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr',
		gap: toRem(14),
	},
	formRowFull: {
		gridColumn: '1 / -1',
	},
	input: {
		width: '100%',
		padding: `${toRem(12)} ${toRem(14)}`,
		borderRadius: toRem(12),
		border: `1px solid ${colors.inputBorder}`,
		backgroundColor: colors.labelBG,
		color: colors.white,
		outline: 'none',
		fontSize: toRem(14),
	},
	textarea: {
		width: '100%',
		minHeight: toRem(100),
		padding: `${toRem(12)} ${toRem(14)}`,
		borderRadius: toRem(12),
		border: `1px solid ${colors.inputBorder}`,
		backgroundColor: colors.labelBG,
		color: colors.white,
		outline: 'none',
		fontSize: toRem(14),
		resize: 'vertical',
	},
	statusCard: {
		backgroundColor: 'rgba(255,255,255,0.04)',
		borderRadius: toRem(14),
		padding: toRem(18),
		textAlign: 'center',
	},
	statusText: {
		opacity: 0.75,
		lineHeight: 1.6,
	},
});
