import { colors, toRem } from "../../../../styles/commonStyle";

export const createCalendarStyles = (mainColor) => ({
	calendareSection: {
		position: 'relative',
		zIndex: 1,
	},
	previewCard: {
		width: '100%',
		border: 'none',
		borderRadius: toRem(16),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(16),
		cursor: 'pointer',
		textAlign: 'left',
		color: colors.white,
	},
	previewHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		gap: toRem(12),
	},
	previewEyebrow: {
		fontSize: toRem(12),
		letterSpacing: '0.08em',
		textTransform: 'uppercase',
		color: `${colors.white}99`,
		margin: 0,
	},
	previewMonth: {
		fontSize: toRem(20),
		fontWeight: 700,
		margin: `${toRem(4)} 0 0`,
	},
	countBadge: {
		padding: `${toRem(8)} ${toRem(12)}`,
		borderRadius: toRem(999),
		backgroundColor: `${mainColor || colors.green}22`,
		color: mainColor || colors.green,
		fontSize: toRem(12),
		fontWeight: 700,
		whiteSpace: 'nowrap',
	},
	weekGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
		gap: toRem(8),
	},
	weekDayCard: {
		borderRadius: toRem(14),
		padding: `${toRem(12)} ${toRem(8)}`,
		backgroundColor: `${colors.white}08`,
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: toRem(10),
		border: `1px solid transparent`,
	},
	weekDayCardMobile: {
		gap: toRem(4),
		padding: `${toRem(8)} ${toRem(8)}`,
	},
	weekDayLabel: {
		fontSize: toRem(11),
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		color: `${colors.white}80`,
	},
	weekDayNumber: {
		fontSize: toRem(24),
		fontWeight: 700,
		lineHeight: 1,
	},
	weekDayNumberSmall: {
		fontSize: toRem(18),
	},
	trainingDot: {
		width: toRem(8),
		height: toRem(8),
		borderRadius: '50%',
		backgroundColor: colors.blueLight,
		boxShadow: `0 0 12px ${(colors.blueLight)}aa`,
	},
	statusText: {
		fontSize: toRem(14),
		color: `${colors.white}c0`,
		margin: 0,
	},
	retryButton: {
		marginTop: toRem(12),
		background: 'transparent',
		border: `1px solid ${mainColor || colors.green}`,
		color: mainColor || colors.green,
		borderRadius: toRem(999),
		padding: `${toRem(8)} ${toRem(14)}`,
		cursor: 'pointer',
		fontWeight: 700,
	},
	modal: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(18),
		color: colors.white,
	},
	modalHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: toRem(12),
	},
	modalTitle: {
		fontSize: toRem(22),
		fontWeight: 700,
		margin: 0,
	},
	modalSubtitle: {
		fontSize: toRem(13),
		color: `${colors.white}99`,
		margin: `${toRem(4)} 0 0`,
	},
	modalActions: {
		display: 'flex',
		alignItems: 'center',
		gap: toRem(8),
	},
	iconButton: {
		width: toRem(38),
		height: toRem(38),
		borderRadius: '50%',
		border: `1px solid ${colors.white}22`,
		backgroundColor: `${colors.white}08`,
		color: colors.white,
		cursor: 'pointer',
		fontSize: toRem(18),
	},
	calendarShell: {
		backgroundColor: `${colors.blueDark}d9`,
		borderRadius: toRem(18),
		padding: toRem(16),
	},
	monthHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: toRem(16),
		gap: toRem(12),
	},
	monthTitle: {
		fontSize: toRem(18),
		fontWeight: 700,
		margin: 0,
	},
	weekdayRow: {
		display: 'grid',
		gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
		gap: toRem(8),
		marginBottom: toRem(8),
	},
	weekdayCell: {
		textAlign: 'center',
		fontSize: toRem(11),
		fontWeight: 700,
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		color: `${colors.white}80`,
	},
	monthGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(7, minmax(0, 1fr))',
		gap: toRem(8),
	},
	monthDay: {
		borderRadius: toRem(14),
		padding: `${toRem(10)} ${toRem(8)}`,
		backgroundColor: `${colors.white}06`,
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'center',
		border: `1px solid ${colors.white}08`,
	},
	monthDayNumber: {
		fontSize: toRem(16),
		fontWeight: 700,
	},
	monthDayText: {
		fontSize: toRem(11),
		color: `${colors.white}80`,
	},
	trainingPill: {
		fontSize: toRem(10),
		fontWeight: 700,
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
		color: colors.black,
		backgroundColor: mainColor || colors.green,
		padding: `${toRem(4)} ${toRem(8)}`,
		borderRadius: toRem(999),
	},
	emptyState: {
		fontSize: toRem(14),
		color: `${colors.white}b3`,
		margin: 0,
	},
});
