import { colors, toRem } from '../../../styles/commonStyle';

export const createProgressStyles = (mainColor) => ({
	main: {
		padding: toRem(18),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(20),
		paddingBottom: toRem(123),
	},
	section: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
	},
	progressBarSectionCard: {
		display: 'grid',
		alignItems: 'center',
		gridTemplateColumns: '90px 1fr 65px',
		gap: toRem(10),
	},
	card: {
		backgroundColor: colors.labelBG,
		borderRadius: toRem(14),
		padding: toRem(18),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
		boxShadow: `0 2px 0 ${mainColor || colors.green}`,
	},
	overallCardLayout: {
		display: 'grid',
		gridTemplateColumns: '1fr',
		gap: toRem(18),
		alignItems: 'center',
	},
	overallCardLayoutTablet: {
		gridTemplateColumns: '1fr',
	},
	overallCardContent: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
		minWidth: 0,
	},
	overallVisualBlock: {
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		gap: toRem(12),
	},
	statsGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
		gap: toRem(10),
	},
	statItem: {
		backgroundColor: 'rgba(255, 255, 255, 0.04)',
		borderRadius: toRem(12),
		padding: toRem(12),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(6),
	},
	statLabel: {
		fontSize: toRem(13),
		opacity: 0.7,
	},
	statValue: {
		fontSize: toRem(24),
		fontWeight: 700,
		lineHeight: 1.1,
	},
	statValuePositive: {
		color: mainColor || colors.green,
	},
	statValueNegative: {
		color: colors.red,
	},
	subtitle: {
		fontSize: toRem(14),
		opacity: 0.75,
	},
	muscleGroupGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
		gap: toRem(12),
	},
	muscleGroupCard: {
		backgroundColor: colors.labelBG,
		borderRadius: toRem(14),
		padding: toRem(16),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(12),
		border: `1px solid ${mainColor || colors.green}22`,
	},
	muscleGroupName: {
		fontSize: toRem(18),
		fontWeight: 700,
	},
	progressBarSectionValue: {
		fontSize: toRem(16),
	},
	exerciseStatsList: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(12),
	},
	exerciseGroupList: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
	},
	titleHeader: {
		alignItems: 'flex-start',
		marginBottom: toRem(0),
		marginTop: toRem(20),
	},
	exerciseGroupCard: {
		backgroundColor: colors.labelBG,
		borderRadius: toRem(14),
		padding: toRem(16),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(14),
		border: `1px solid ${mainColor || colors.green}22`,
	},
	exerciseGroupHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: toRem(12),
	},
	exerciseSearchWrap: {
		display: 'flex',
	},
	exerciseSearchInput: {
		width: '100%',
		borderRadius: toRem(12),
		border: `1px solid ${mainColor || colors.green}44`,
		backgroundColor: colors.labelBG,
		color: colors.white,
		padding: `${toRem(12)} ${toRem(14)}`,
		fontSize: toRem(15),
		outline: 'none',

	},
	exerciseStatCard: {
		backgroundColor: 'rgba(255, 255, 255, 0.03)',
		borderRadius: toRem(14),
		padding: toRem(16),
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(12),
		border: `1px solid ${mainColor || colors.green}22`,
	},
	exerciseStatLayout: {
		display: 'grid',
		gridTemplateColumns: 'minmax(0, 1fr) auto minmax(0, 1fr)',
		gap: toRem(16),
		alignItems: 'center',
	},
	exerciseStatContent: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(12),
		minWidth: 0,
	},
	exerciseStatHeader: {
		display: 'flex',
		alignItems: 'center',
		gap: toRem(12),
	},
	exerciseStatNameBlock: {
		display: 'flex',
		flexDirection: 'column',
		gap: toRem(4),
		minWidth: 0,
	},
	exerciseVisualBlock: {
		display: 'flex',
		justifyContent: 'end',
	},
	exerciseRange: {
		fontSize: toRem(16),
		fontWeight: 600,
		opacity: 0.9,
	},
	ellipseProgressWrap: {
		position: 'relative',
		width: toRem(220),
		height: toRem(220),
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	ellipseProgressSvg: {
		transform: 'rotate(-90deg)',
		overflow: 'visible',
	},
	ellipseProgressTrack: {
		fill: 'none',
		stroke: 'rgba(255, 255, 255, 0.08)',
		strokeWidth: toRem(24),
	},
	ellipseProgressFill: {
		fill: 'none',
		stroke: mainColor || colors.green,
		strokeWidth: toRem(24),
		strokeLinecap: 'round',
		transition: 'stroke-dashoffset 0.4s ease, stroke 0.3s ease',
		transformOrigin: 'center',
	},
	ellipseProgressCenter: {
		position: 'absolute',
		inset: 0,
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		gap: toRem(6),
		textAlign: 'center',
		padding: toRem(20),
	},
	ellipseProgressValue: {
		fontSize: toRem(32),
		fontWeight: 800,
		lineHeight: 1,
		color: mainColor,
	},
	ellipseProgressLabel: {
		fontSize: toRem(24),
		opacity: 0.72,
		textTransform: 'uppercase',
		letterSpacing: '0.08em',
	},
	progressBarTrack: {
		width: '100%',
		height: toRem(14),
		borderRadius: toRem(999),
		backgroundColor: 'rgba(255, 255, 255, 0.08)',
		overflow: 'hidden',
	},
	progressBarFill: {
		height: '100%',
		borderRadius: toRem(999),
		backgroundColor: mainColor || colors.green,
		transition: 'width 0.4s ease, background-color 0.3s ease',
	},
	progressPositive: {
		color: mainColor || colors.green,
		backgroundColor: mainColor || colors.green,
		stroke: mainColor || colors.green,
	},
	progressNegative: {
		color: colors.red,
		backgroundColor: colors.red,
		stroke: colors.red,
	},
	progressNeutral: {
		color: colors.white,
		backgroundColor: colors.white,
		stroke: colors.white,
	},
	statusCard: {
		backgroundColor: colors.labelBG,
		borderRadius: toRem(14),
		padding: toRem(20),
		textAlign: 'center',
	},
	statusText: {
		fontSize: toRem(15),
		opacity: 0.8,
	},
});
